name: wimb
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0
  geolocator: ^9.0.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  shared_preferences: ^2.2.1
  go_router: ^12.0.0
  flutter_hooks: ^0.20.0
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # Add this line

flutter_icons:
  android: "ic_launcher"  # Default target name (no need to change)
  ios: true
  image_path: "assets/Logo3.png"  # Your custom file name

flutter:
  uses-material-design: true
  assets:
    - assets/Logo2.png
flutter_launcher_name:
  name: "Where is My Bus ?"  # Your desired app name